retailer:
  monoprix:
    nb_levels: 5
    level0: ['BOUCHERIE VOLAILLE', 'CREMERIE', 'BEAUTY WEEK', 'PARAPHARMACIE', 'PRODUIT DE LA MER', 'TRAITEUR', 'SURGELES', 'ENTRETIEN', 'EPICERIE SALEE', 'FRUIT LEGUME', 'ANIMAUX', 'EPICERIE SUCREE', 'BOISSON CAVE', 'CHARCUTERIE', 'PAIN VIENNOISERIE', 'NUTRITION DIETETIQUE', 'MAISON', 'HYGIENE BEAUTE', 'BEBE']
    level1_to_delete: 
      - "CAVE"
  franprix:
    nb_levels: 3
    level0: ['SURGELES', 'PRODUITS FRAIS', 'HYGIENE BEAUTE ET BEBE', 'FRUITS ET LEGUMES', 'BIO ET ECOLOGIQUE', 'EPICERIE SUCREE', 'BOISSONS', 'ENTRETIEN ET MAISON', 'EPICERIE SALEE', 'CREMERIE YAOURTS OEUFS']
    level1_to_delete: 
      - "VINS ET CHAMPAGNES"
  auchan:
    nb_levels: 6
    level0: ['TOUT POUR BEBE', 'EPICERIE SUCREE', 'FRUITS LEGUMES', 'PRODUITS LAITIERS OEUFS FROMAGES', 'MEUBLE DECO LINGE DE MAISON', 'PRODUITS DU MONDE ET DE NOS REGIONS', 'JARDIN AUTO BRICO', 'ELECTROMENAGER CUISINE', 'ANIMALERIE', 'HIGH TECH AUDIO TV TELEPHONIE', 'HYGIENE BEAUTE', 'EPICERIE SALEE', 'EAUX JUS SODA THES GLACES', 'JOUETS JEUX VIDEO LIVRES', 'ENTRETIEN ACCESSOIRES DE LA MAISON', 'BOUCHERIE VOLAILLE POISSONNERIE', 'REGIMES ALIMENTAIRES ET NUTRITION', 'MODE BIJOUX BAGAGERIE', 'CHARCUTERIE TRAITEUR PAIN', 'SURGELES', 'HYGIENE BEAUTE PARAPHARMACIE', 'VINS BIERES ALCOOLS', 'MEUBLE LITERIE LINGE DE MAISON', 'BIO ET ECOLOGIQUE']
    level1_to_delete: 
      - "CHAMPAGNES VINS EFFERVESCENTS"
      - "LA GRANDE CAVE AUCHAN"
      - "VINS"
  carrefour:
    nb_levels: 4
    level0: ['CONFORT DE LA MAISON', 'BOULANGERIE/PATISSERIE', 'HOMME', 'FEMME', 'MICRO INFORMATIQUE', 'POISSONNERIE', 'PAPETERIE', 'PEM', 'ACCESSOIRES', 'PARFUMERIE HYGIENE', 'RADIOTELEPHONIE', 'ENFANT', 'JEUX VIDEO ET LOGICIELS', 'AUTO', 'JOUET SPORT', 'BEBE', 'EPICERIE', 'CHAUSSURE', 'PRESSE', 'PARAPHARMACIE', 'FRUITS ET LEGUMES', 'DROGUERIE', 'BRICOLAGE', 'PHOTO COMMUNICATION', 'LIBRAIRIE', 'GEM', 'IMAGE ET SON', 'LINGE DE MAISON', 'NON AFFECTE', 'BOUCHERIE VOLAILLE', 'CHARCUT.TRAITEUR', 'JARDIN ET ANIMALERIE', 'VIDEO', 'CAFETERIA ESPACE RESTAURATION', 'MUSIQUE', 'BIJOUTERIE', 'BOISSONS', 'P.L.S.']
    level1_to_delete: 
      - "VINS"  
  new_brand:
    nb_levels: 3
    level0: []
    level1_to_delete: []

unknown_brands: 
- "AUTRES MARQUES"
- "AUTRE MARQUE"
- "NON RENSEIGNE"
- "NULL"
- "0" 
- "NO NAME" 
- "NO NAME MDD"
- "DEFAULT"
- "SANSMARQUE"
- "SANS MARQUE"
- "BIO"
- 'MARQUE NATIONALE'

sl_replacements : 
- ["&", "et"]
- ["1", "un "]
- ["2", "deux "]
- ["3", "trois "]
- ["4", "quatre "]
- ["5", "cinq "]
- ["6", "six "]
- ["7", "sept "]
- ["8", "huit "]
- ["9", "neuf "]
- ["10", "dix "]

classification_levels: 
  - 0
  - 1
  - 2

classification_most_relevant_levels: 
- 1
- 2

indicators_var:
- "similarity_syntax_ngram"
# - "similarity_classification"
- "similarity_classification_words"
- "fuzzy_ratio"
# - "discounted_levenshtein"
- "lcwords"

label_var :
- "left_side"
- "right_side"

target_var : "target"
